import { Button, VerticalBox, LineEdit, StandardButton } from "std-widgets.slint";
import { Page, ActionButton, PayPage } from "mainpage.slint";

export AppWindow := Window {
    property<int> counter: 42;
    property<string> text: "Hardware Loading...";
    callback request-increase-value();
    callback load-app();
    title: "Doomspay";
    width: 500px;
    height: 400px;
    ActionButton {
         icon: @image-url("images/usb.svg");
         text: "Plug in your hardware wallet" ;
         clicked => {
                text = root.text;
                visible = false;
                PayPage.visible = true;
          }
      }

    PayPage :=  PayPage {
         visible: false;
    }
}
