import { Button, VerticalBox, LineEdit, StandardButton } from "std-widgets.slint";

export AppWindow := Window {
    property<int> counter: 42;
    callback request-increase-value();
    title: "Doomspay";
    width: 300px;
    VerticalBox {
        TextInput {
           font-size: 14px;
           text: "Enter PIN";

        }
        StandardButton{
           kind: ok;
           background: cyan;
           border-radius: 3px;
        }
        StandardButton {
           kind: cancel;
           border-radius: 3px;
        }

     }


}
