//common main page component
import { Button, LineEdit } from "std-widgets.slint";
export Page := Rectangle {

    property <string> header <=> h.text;

    h := Text {
       font-weight: 900;
       color: dodgerblue;
    }
}
Label := Text {
    font-family: "Arial";
    font-weight: 600;
    font-size: 20px;
    color: darkgreen;
}

CustomTextBox := Rectangle {
    border-radius: 25px;
    border-color: red;
    background: orange;
    property <string> text;
    padding-top: 20px;
    padding-left: 50px;
    Text {
        font-size: 20px;
        font-weight: 600;
        color: darkgreen;
        text: root.text;
    }

}

PaymentDetails := Rectangle {
    GridLayout {
         spacing: 5px;
         Row {
            Label {
                 text: "Amount due: ";
            }
            CustomTextBox {
                 text: "0.005sats";
            }
         }

    }
}

export PayPage := Rectangle {

    visible: false;
    callback clicked;

    VerticalLayout {
        spacing: 4px;
        padding-top: 20px;
        padding-bottom: 20px;
        padding-left: 20px;
        padding-right: 20px;
        HorizontalLayout {
            PaymentDetails {}
        }
        Button {
             border-radius: 25px;
             border-width: 1px;
             border-color: gray;
             background: cyan;
             text : "Pay Now";

        }

    }
}

export ActionButton := Rectangle {

    property <image> icon <=> img.source;
    property <string> text <=> label.text;
    callback clicked;

    VerticalLayout {
        spacing: 4px;
        padding-top: 20px;
        padding-bottom: 20px;
        padding-left: 20px;
        padding-right: 20px;

        Rectangle {
            border-radius: 25px;
            border-width: 5px;
            border-color: black;
            background: orange;

            img := Image {
                x: (parent.width / 2) - (self.width / 2);
                y: (parent.height / 2) - (self.height / 2);
                colorize: black;
            }
        }

        label := Text {
            font-size: 10px * 1.375;
            font-weight: 800;
            horizontal-alignment: center;
            color: whitesmoke;
        }
    }

    TouchArea { clicked => { root.clicked() } }

}

