//common main page component
export Page := Rectangle {

    property <string> header <=> h.text;

    h := Text {
       font-weight: 900;
       color: dodgerblue;
    }
}

export ActionButton := Rectangle {

    property <image> icon <=> img.source;
    property <string> text <=> label.text;
    callback clicked;

    VerticalLayout {
        spacing: 4px;
        padding-top: 20px;
        padding-bottom: 20px;
        padding-left: 20px;
        padding-right: 20px;

        Rectangle {
            border-radius: 25px;
            border-width: 5px;
            border-color: black;
            background: orange;

            img := Image {
                x: (parent.width / 2) - (self.width / 2);
                y: (parent.height / 2) - (self.height / 2);
                colorize: black;
            }
        }

        label := Text {
            font-size: 10px * 1.375;
            font-weight: 800;
            horizontal-alignment: center;
            color: black;
        }
    }

    TouchArea { clicked => { root.clicked() } }
}